name: simple_todo_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  persistent_bottom_nav_bar: ^4.0.2
  cupertino_icons: ^1.0.3
  carousel_slider: ^4.0.0-nullsafety.0
  day_night_time_picker: ^1.0.2
  implicitly_animated_reorderable_list: ^0.4.0
  flutter_slidable: ^0.6.0

  easy_localization: ^3.0.0
  async: ^2.6.1
  uuid: 3.0.4
  shared_preferences: ^2.0.6
  provider: ^5.0.0
  flutter_screenutil: ^5.0.0+2

  hive: ^2.0.4
  path_provider: ^2.0.2

  firebase_core: ^1.2.1
  firebase_auth: ^1.3.0
  google_sign_in: ^5.0.4

  device_preview: ^0.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^1.1.0
  build_runner: ^2.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/localizations/