name: tasks_go_brr
description: haha Tasks go brr.

publish_to: 'none'

version: 0.3.2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  persistent_bottom_nav_bar: ^4.0.2
  cupertino_icons: ^1.0.3
  day_night_time_picker: ^1.0.2
  implicitly_animated_reorderable_list_2: ^0.5.1
  flutter_slidable: ^0.6.0
  weekday_selector: ^1.0.0
  animated_size_and_fade: ^3.0.0
  sleek_circular_slider: ^2.0.1
  numberpicker: ^2.1.1
  fl_chart: ^0.45.0
  auto_size_text: ^3.0.0-nullsafety.0
  shimmer: ^3.0.0
  visibility_detector: ^0.4.0+2

  easy_localization: ^3.0.0
  async: ^2.6.1
  uuid: ^4.2.1
  shared_preferences: ^2.0.6
  provider: ^6.1.1
  flutter_screenutil: ^5.0.0+2
  in_app_review: ^2.0.2
  url_launcher: ^6.1.14
  package_info_plus: ^4.2.0
  image_picker: ^1.0.4
  flutter_colorpicker: ^1.0.3

  android_alarm_manager_plus: ^3.0.4
  flutter_local_notifications: ^16.2.0

  hive: ^2.0.4
  path_provider: ^2.0.2

  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  google_sign_in: ^6.1.6
  cloud_firestore: ^4.9.3
  firebase_storage: ^11.2.8

  firebase_crashlytics: ^3.3.7

  in_app_purchase: ^3.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.1
  build_runner: ^2.0.4

  flutter_native_splash: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/localizations/
    - assets/icons/
    - assets/images/
    - android/app/src/main/res/drawable/ic_app_full.png

  fonts:
    - family:  IconsSoft
      fonts:
        - asset: assets/IconsSoft.ttf

flutter_native_splash:
  color: "#F3F3F3"
  image: android/app/src/main/res/drawable/ic_splash.png

  color_dark: "#121212"
  image_dark: android/app/src/main/res/drawable/ic_splash.png