name: tasks_go_brr
description: haha Tasks go brr.

publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  persistent_bottom_nav_bar: ^4.0.2
  cupertino_icons: ^1.0.3
  day_night_time_picker: ^1.0.2
  implicitly_animated_reorderable_list: ^0.4.0
  flutter_slidable: ^0.6.0
  weekday_selector: ^1.0.0
  animated_size_and_fade: ^2.0.0
  sleek_circular_slider: ^2.0.1
  numberpicker: ^2.1.1
  fl_chart: ^0.36.2
  auto_size_text: ^3.0.0-nullsafety.0
  shimmer: ^2.0.0
  visibility_detector: ^0.2.0

  easy_localization: ^3.0.0
  async: ^2.6.1
  uuid: 3.0.4
  shared_preferences: ^2.0.6
  provider: ^5.0.0
  flutter_screenutil: ^5.0.0+2
  in_app_review: ^2.0.2
  url_launcher: ^6.0.9
  package_info: ^2.0.2
  image_picker: ^0.8.2
  flutter_colorpicker: ^0.4.0

  android_alarm_manager_plus: ^1.0.2
  flutter_local_notifications: ^6.0.0

  hive: ^2.0.4
  path_provider: ^2.0.2

  firebase_core: ^1.2.1
  firebase_auth: ^1.3.0
  google_sign_in: ^5.0.4
  cloud_firestore: ^2.3.0
  firebase_storage: ^10.0.1

  device_preview: ^0.7.3
  firebase_crashlytics: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^1.1.0
  build_runner: ^2.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/localizations/
    - assets/icons/
    - assets/images/
    - android/app/src/main/res/drawable/ic_app_full.png

  fonts:
    - family:  IconsSoft
      fonts:
        - asset: assets/IconsSoft.ttf