// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt7zSjDRWeZmWnZMNXDWQtQMC8pNFUfUQ',
    appId: '1:738589446558:android:19b70b0f516c52f22cc68f',
    messagingSenderId: '738589446558',
    projectId: 'simple-todo-1d4e8',
    storageBucket: 'simple-todo-1d4e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8fncOkXLBNePyWQmUSs183Eyx_4xgR-g',
    appId: '1:738589446558:ios:6de41905bbd374812cc68f',
    messagingSenderId: '738589446558',
    projectId: 'simple-todo-1d4e8',
    storageBucket: 'simple-todo-1d4e8.appspot.com',
    androidClientId: '738589446558-fpublfmhctp5qv6ilegc6tgvqul11435.apps.googleusercontent.com',
    iosClientId: '738589446558-9sbag381rnona8fgd6a9corcgent2imh.apps.googleusercontent.com',
    iosBundleId: 'com.khudolii.tasksgobrr',
  );

}